@port=5038

GET http://localhost:{{port}}/Test
Accept: application/json

###
POST http://localhost:{{port}}/Test
Accept: application/json

###
PATCH http://localhost:{{port}}/Test
Accept: application/json

###
DELETE http://localhost:{{port}}/Test
Accept: application/json